alert("open website in pc or laptop")
alert("please provide feedback through contact form below")
document.querySelector(".burgerimg1").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/amirali-mirhashemian-jh5XyK4Rr3Y-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg1").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/classic.png")})
document.querySelector(".burgerimg2").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/chad-montano--GFCYhoRe48-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg2").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/cheese.png")})
document.querySelector(".burgerimg3").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/eiliv-aceron-uBigm8w_MpA-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg3").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/aceron.png")})
document.querySelector(".burgerimg4").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/food-photographer-E94j3rMcxlw-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg4").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/veg.png")})
document.querySelector(".burgerimg5").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/israel-albornoz-YFG2_ZYoMWQ-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg5").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/mushroom.png")})
document.querySelector(".burgerimg6").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/lefteris-kallergis-rbcvIrxw6KA-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg6").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/veg.png")})
document.querySelector(".burgerimg7").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/lucas-andrade-1rC6Uo2Eevc-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg7").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/red.png")})
document.querySelector(".burgerimg8").addEventListener("click",function(){document.querySelector(".burger").setAttribute("src","images/eiliv-aceron-5nvt9BrLaAc-unsplash-removebg-preview.png")})
document.querySelector(".burgerimg8").addEventListener("click",function(){document.querySelector(".textcard").setAttribute("src","images/text/cheese.png")})